module.exports.categories = [
  "Ortofrutta",
  "Carne",
  "Pesce",
  "Salumi e Formaggi",
  "Pasta, Riso, Cereali, Farine",
  "Pane e prodotti da forno",
  "Vino e altre bevande alcoliche",
  "Bevande analcoliche",
  "Altro",
];
module.exports.country = [
  "Abruzzo",
  "Basilicata",
  "Calabria",
  "Campania",
  "Emilia-Romagna",
  "Friuli-Venezia Giulia",
  "Lazio",
  "Liguria",
  "Lombardia",
  "Marche",
  "Molise",
  "Piemonte",
  "Puglia",
  "Sardegna",
  "Sicilia",
  "Toscana",
  "Trentino-Alto Adige",
  "Umbria",
  "Valle d'Aosta",
  "Veneto",
];
